# Generated by Django 3.1.7 on 2022-02-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='¿Es activo?')),
                ('date_record', models.DateField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('date_update', models.DateField(auto_now=True, verbose_name='Fecha de actualización')),
                ('id_unplash', models.CharField(max_length=255)),
                ('preview', models.CharField(max_length=255)),
                ('favorite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_record', '-date_update'],
                'get_latest_by': 'date_record',
                'abstract': False,
            },
        ),
    ]
